- docs/sphinx/api/tools.rst
- python/marvin/__init__.py
- python/marvin/api/maps.py
- python/marvin/api/spaxel.py
- python/marvin/tests/tools/test_bin.py
- python/marvin/tests/tools/test_maps.py
- python/marvin/tests/tools/test_spaxel.py
- python/marvin/tools/analysis_props.py
- python/marvin/tools/bin.py
- python/marvin/tools/maps.py
- python/marvin/tools/modelcube.py
- python/marvin/tools/spaxel.py
This pull request includes changes to `Spaxel` and implements the new `Bin` class. `Spaxel` has now been modified to only represent spaxels from unbinned maps/modelcubes. This can be overridden using the `allow_binned=True` parameter, but it's not the default behaviour. This change does not seem to have broken anything, but any additional test would be good, as a fair amount of things depend on `Spaxel`.
`Bin` is still a pretty basic implementation but it contains all the critical bits, and can be extended after the beta release.
> New bin class

- python/marvin/api/general.py
- python/marvin/core/core.py
- python/marvin/tests/tools/test_cube.py
- python/marvin/tests/utils/test_general.py
- python/marvin/tools/cube.py
- python/marvin/tools/maps.py
- python/marvin/tools/modelcube.py
- python/marvin/tools/rss.py
- python/marvin/utils/general/general.py
This PR adds a `.nsa` property to `MarvinToolsClass` (i.e., it can be accessed from `Cube`, `Maps`, `ModelCube`, and `RSS`) to access NSA information for the target. The retrieval of the NSA data itself is handled via a new function, `get_nsa_data`, in `marvin.utils.general.general`. The function allows to obtain the information from the drpall file or from `mangaSampleDB.NSA`. For each object, the default access mode is defined by a new kwarg `nsa_source`
```
nsa_source ({'auto', 'drpall', 'nsa'}):
Defines how the NSA data for this object should loaded when
``Cube.nsa`` is first called. If ``drpall``, the drpall file will
be used (note that this will only contain a subset of all the NSA
information); if ``nsa``, the full set of data from the DB will be
retrieved. If the drpall file or a …
```
> Adds NSA information to MarvinToolsClass derivates

- python/marvin/tests/tools/test_cube.py
- python/marvin/tests/tools/test_maps.py
- python/marvin/tests/tools/test_modelcube.py
- python/marvin/tools/map.py
This should fix #148, at least temporarily. The individual maps returned by the DB (and, thus, also by the API) are transposed. A simple `.T` in the returned array solves the problem. I have added test to `test_cube` and `test_maps` to check that the returned values (flux, ivar, mask) from file, db, and API agree and match what one expects from the file when opening it with astropy. This problems seems to affect only to maps, the spectra from cubes are correctly returned in all cases.
Moving forward, we can either keep this fix or, probably better, flip the x and y columns in spaxelprop and spaxelprop5 (I think that should have the same effect as transposing the array).
> Fix incorrect orientation of Maps returned from DB and API

- python/marvin/core/core.py
- python/marvin/tests/tools/test_cube.py
- python/marvin/tests/tools/test_spaxel.py
- python/marvin/tools/bin.py
- python/marvin/tools/map.py
- python/marvin/tools/spaxel.py
This fixes both #152 and #138. It simply adds a new property to `MarvinToolClass` that returns `_release` but fails if you try to set the property.
> Added release property

- CHANGELOG.md
- python/marvin/__init__.py
- python/marvin/db/marvindb.py
- python/marvin/db/models/DataModelClasses.py
- python/marvin/tests/tools/test_query.py
- python/marvin/tests/tools/test_results.py
- python/marvin/tools/query/__init__.py
- python/marvin/tools/query/query.py
- python/marvin/tools/query/results.py
This resolves #162 #161.   I have updated the Query mode to raise an error if the mode is local if there is no database.  If the mode is remote and there is no urlmap it will also raise an error.  Query no longer switches the mode automatically to remote.  The query still explicitly passes its mode into Results.  The Results has no decision tree of its own.  
I've added a mode keyword option into the convertToTool method.  This allows the user to explicitly set how they want to convert the tools independent of the query or results.  Doing `r.convertToTool("cube", mode="auto")` will use `auto` during conversion and produce a mix of files and api data_origins if you have them.  If not set, this keyword defaults to the internal mode set inside Results. 
I've added a toCSV method into the …
> updated query mode to better reflect config.mode and not change

- python/marvin/api/cube.py
- python/marvin/core/core.py
- python/marvin/tests/tools/test_cube.py
- python/marvin/tools/cube.py
This PR removes the automatic loading of redshift in `Cube` to avoid problems with galaxies not in the NSA (e.g., 7443-12701 reported in #129).
The key is that we want this change to not break backwards compatibility with the API for previous versions of Marvin. The API side of `getCube` now check whether it can grab the NSA information and, if it cannot, it returns `redshift=-1`. If the NSA is available it returns `cube.nsa.z` (this will not be used by marvin>=2.1, but it will for previous versions).
In `Cube` I have removed all loading of redshift. The redshift should now be accessed via `cube.nsa.[z/redshift]`.
I have added a few tests for 7443-12701 and tried to test it in an order such that I think it will work when Utah is running 2.1 and an user is running 2.0.9. But we should …
> NSA fix for 7443

- CHANGELOG.md
- docs/sphinx/known-issues.rst
- docs/sphinx/tools/bpt.rst
- python/marvin/core/exceptions.py
- python/marvin/tests/utils/test_bpt.py
- python/marvin/tools/maps.py
- python/marvin/utils/dap/bpt.py
This should fix #188. `snr` is now deprecated in favour of `snr_min`. If `snr` is used, a `MarvinDeprecationWarning` is issued and the value of `snr` is used for `snr_min`. At some point we may want to remove `snr` completely.
I have updated the tests and the documentation.
> snr to snr_min for BPT

- python/marvin/__init__.py
- python/marvin/api/__init__.py
- python/marvin/api/cube.py
- python/marvin/api/general.py
- python/marvin/api/query.py
- python/marvin/db/sql/mangadapdb.sql
- python/marvin/db/sql/mangadatadb.sql
- python/marvin/tests/tools/test_cube.py
- python/marvin/tools/cube.py
This is now implemented in the `flux_api` (regardless of the name of the branch note that this works for flux, ivar, and mask). With a good internet connection, retrieving the flux for a 127-fibre cube takes about 40 seconds, which seems reasonable. The values are cached so the API call will happen only once per extension (flux, ivar, mask).
@havok2063 needs to look into why the `getCubeExtension` in `api/cube.py` does not work with the validators. Also, right now I'm grabbing the release directly from the request instead of using the validator arg.
Fixes #236
> Make cube.flux work in remote mode

- CHANGELOG.md
- docs/sphinx/tools/cube.rst
- docs/sphinx/tools/maps.rst
- docs/sphinx/tools/modelcube.rst
- docs/sphinx/whats-new.rst
- python/marvin/tests/tools/test_cube.py
- python/marvin/tests/tools/test_maps.py
- python/marvin/tests/tools/test_modelcube.py
- python/marvin/tools/cube.py
- python/marvin/tools/maps.py
- python/marvin/tools/modelcube.py
I have inverted `__getitem__` in Cube, Maps, and ModelCube to mean
```python
cube[4, 5] == cube.getSpaxel(x=5, y=4, xyorig='lower')
```
and fixed the tests.
@havok2063 I have had a look at the web and it seems ok. I think slicing is not used in `galaxy.py` but I may be wrong. Can you have a quick look?
This fixes #243
> Issue #243: inverted `__getitem__` and fixed tests

- python/marvin/core/exceptions.py
The use of os.getlogin() has known [troubles](https://mail.python.org/pipermail/python-bugs-list/2002-July/012691.html) where the shell can't query the C library's getlogin() (e.g., when run under cron). This tripped on my local linux (Mint 18.3/Ubuntu 16.04+Python3.5) when running under the standard Gnome Terminal. The recommended solution is to use `pwd.getpwuid(os.getuid())[0]`. A quick grock of the codebase only shows this one instance of 'getlogin'.
> Avoid known os.getlogin() bug

- python/marvin/__init__.py
setMPL and setDR have explicit format checks that are already handled by the version setter in the class These checks would also introduce spurious errors if DR20 or MPL10 were to arrive. This will likely effect #221.
If marvin has a deprecation mechanism, these could be deprecated as setRelease does all of the necessary work.
> Remove redundant and unmaintainable format checks for version.

- CHANGELOG.rst
- python/marvin/tests/utils/plot/test_map.py
- python/marvin/utils/dap/bpt.py
Fixes #400
This simply uses the sum of both SII lines instead of just SII 6718. No tests seem have been affected by this, which of course means that our tests are not good enough.
> Uses sum of both SII lines for BPT

- python/marvin/__init__.py
- python/marvin/core/core.py
- python/marvin/db/database.py
- python/marvin/utils/general/images.py
- python/marvin/utils/general/yanny.py
Python 3.7 comes with a few annoying deprecation warnings. This should fix it. I have also removed a few other, old warnings that we were ignoring or suffering.
Also, this PR updates tree, sdss_access, and marvin_brain to a version in which the redirection of warnings to the log is disabled. It seems we have multiple logging systems that, each one of them, override `warnings._show_warnings` and, as a result, cause a fair amount of trouble and missed warnings. I have to think of a better way to implement this, but for now i think it's best to disable it and, if necessary, use `log.warnings` to raise a warnings that will be logged.
> Remove warnings in Python 3.7

- python/marvin/utils/general/maskbit.py
Every time `Maskbits` is called it has to read the maskbits yanny file, which is very slow. This small change stores the yanny file in memory the first time it is read and reuses it from there one. Note that this may be a temporary solution but for now it cuts the import time in half and helps with #442.
> Read yanny file only once

- python/marvin/__init__.py
- python/marvin/tests/test_imports.py
- python/marvin/tools/__init__.py
I got a bit tired of having to import each tool independently, e.g.
```python
from marvin.tools.cube.Cube
from marvin.tools.maps.Maps
...
```
I have added a few imports in the `__init__.py` so that now everything is accessible from the `marvin` namespace. You can now do
```python
import marvin
my_cube = marvin.tools.cube.Cube('8485-1901')
```
and even
```python
import marvin
my_cube = marvin.tools.Cube('8485-1901')
```
It seems to work fine in Python 2 and 3, doesn't break anything, and it doesn't slow things down as far as I can say. I added a few tests.
> Provide quick import access to Marvin Tools

- CHANGELOG.rst
- docs/sphinx/whats-new.rst
- python/marvin/tests/tools/test_spaxel.py
- python/marvin/tools/spaxel.py
> Fix coordinates bug when loading spaxels in Bin

- CHANGELOG.rst
- python/marvin/tests/tools/test_spaxel.py
- python/marvin/tools/spaxel.py
Fixes #465 
As discussed, this removes the targeting bits (`manga_targetX` and `target_flags`) from `SpaxelBase`.
- [n/a] Updates the documentation accordingly.
- [n/a] If relevant, adds a new entry to the [What's new?](https://github.com/sdss/marvin/blob/master/docs/sphinx/whats-new.rst) page.
> Remove targeting bits from SpaxelBase

- CHANGELOG.rst
- docs/sphinx/known-issues.rst
- docs/sphinx/web.rst
- docs/sphinx/whats-new.rst
- python/marvin/core/exceptions.py
- python/marvin/db/models/DapModelClasses.py
- python/marvin/tests/tools/test_map.py
- python/marvin/tests/web/test_galaxy.py
- python/marvin/tools/maps.py
- python/marvin/tools/quantities/map.py
- python/marvin/utils/general/general.py
- python/marvin/web/controllers/galaxy.py
Also applies the correction to the `stellar_sigma` and `emline_gsigma` web maps.  Adds 'Corrected' to the map title.  
Fixes #478
> raises error when applying stellar sigma correction in MPL-6

- CHANGELOG.rst
- python/marvin/db/models/DapModelClasses.py
- python/marvin/tests/conftest.py
- python/marvin/tests/tools/test_query.py
- python/marvin/tools/query.py
- python/marvin/tools/results.py
- python/marvin/utils/datamodel/query/MPL.py
Fixes #484.  In addition, bug fixes the query datamodel and modelclasses to eliminate new extraneous parameters.  This fixes many prior broken query tests.  Also includes additional fixes for in `Results.convertToTool` to fix tests.  There are three remaining MPL-4 query tests that fail due to #482.
> Fix for bug when explicitly returning default parameters in query

- python/marvin/tests/tools/test_aperture.py
- python/marvin/tools/mixins/aperture.py
Fixes #493 
- [n/a] Updates the [CHANGELOG](https://github.com/sdss/marvin/blob/master/CHANGELOG.rst).
> Add mask parameter to getSpaxels

- CHANGELOG.rst
- python/marvin/tests/utils/plot/test_map.py
- python/marvin/utils/plot/map.py
Fixes #510 
The conversion of spaxel coordinates to sky coordinates incorrectly resulted in sky coordinates that were too large by a factor of 2. This is now fixed.
> Fixes bug in map plotting using sky coordinates

- CHANGELOG.rst
- python/marvin/utils/datamodel/query/base.py
Fixes #563
This just casts the keys over which we are iterating to a list so that if the dictionary changes we don't get an error. I think this is only a problem with 3.6+. A different issue is why we need to do a remote call for each query data model even if we are only getting a `Maps` but let's deal with that separately.
> Cast keys to a list to avoid error when key list changes

- CHANGELOG.rst
- python/marvin/tests/tools/test_spaxel.py
- python/marvin/tools/cube.py
- python/marvin/tools/maps.py
- python/marvin/tools/modelcube.py
- python/marvin/tools/spaxel.py
- python/marvin/utils/general/structs.py
- python/marvin/web/controllers/galaxy.py
Fixes #525
Introduces a `gunzip` context manager. When a `Cube` or `ModelCube` is instantiated from a file, it gunzips the whole file to a temporary location from where it's read. The temporary file is destroyed when not needed anymore. This significantly speeds up subsequent accesses to the data stored in the file. The only downside is that the initial creation of the object takes a bit longer, especially for files of large IFUs.
> Gunzip files temporarily

- docs/sphinx/tools/maps.rst
Add discussion of fuzzy string-matching to maps.rst, including an example silent failure matching 'H-beta' to 'Heta_3836'
Updates docs for fuzzy retrieval of maps discussed in #676 
- [y] Has a title that summarises what is changing.
- [y] Updates the documentation accordingly.
- [N/A] Has unit tests & [code coverage](https://coveralls.io/github/sdss/marvin) is not adversely affected (within reason).
- [N/A] Works with Python 2.7 and 3.6 (and ideally with Python 3.7).
- [N/A] Updates the [CHANGELOG](https://github.com/sdss/marvin/blob/master/CHANGELOG.rst).
- [N/A] Removes more lines of code than it adds.
- [N/A] If relevant, adds a new entry to the [What's new?](https://github.com/sdss/marvin/blob/master/docs/sphinx/whats-new.rst) page.
> Update Maps docs: fuzzy string-matching discussion

- CHANGELOG.rst
- python/marvin/web/templates/galaxy.html
Fixes #711, a bug in the galaxy page when no nsa dictionary exists for a given plate-ifu, preventing the quality and target flag modals from popping up.
> Fix on galaxy page when no nsadict available

- python/marvin/__init__.py
- python/marvin/data/marvin.yml
- python/marvin/web/settings.py
This PR turns off Sentry inside marvin.  I rarely check this and don't have time to maintain it.  The Sentry SDK needs to be updated in Marvin anyways.  Leaving the code in place just in case we ever want to re-enable it.   To be merged after #747 .
> Turns off Sentry for final release

- CHANGELOG.rst
- python/marvin/tools/core.py
This fixes a bug in the MarvinTools core `close` method, when objects used as contextmanager.
> Bug fix in Marvin Tools class

- python/marvin/contrib/vacs/base.py
- python/marvin/contrib/vacs/galaxyzoo.py
- python/marvin/contrib/vacs/visual_morph.py
- python/marvin/tools/vacs.py
- python/marvin/web/controllers/galaxy.py
- python/marvin/web/templates/galaxy.html
- python/marvin/web/uwsgi_conf_files/base.ini
- setup.cfg
This PR hides the Visual Morphology VAC from Marvin for DR17.   Additionally, it adds the ability to use the `VACs.check_target` or an individual VAC `has_target` methods in a "low-memory" mode.  In this mode, it accesses the individual FITS data extension as a context manager and deletes the HDU from memory immediately afterwards.  This is useful when needing to open a large VAC file in a low-memory environment, e.g. by a web server. 
Since I'm not quite comfortable with the IO involved in opening ~6 VAC files for every hit of the galaxy web page, I'm hiding the web display of the VAC "is target available" check until a better solution can be implemented.
It also updates the pinned version of some of Marvin's dependencies. 
It also bumps the memory of the web application.
> More fixes for VACs 

- python/marvin/tools/vacs.py
- python/marvin/web/controllers/galaxy.py
- python/marvin/web/templates/galaxy.html
This PR has more fixes and updates to the VAC code.  Adds new `match_targets` method on `VACs` tool to check a list of mangaids against all VACs for a given Marvin release.
> New VAC method and updates to VAC web display 

- .bumpversion.cfg
- CHANGELOG.rst
- docs/sphinx/web.rst
- docs/sphinx/whats-new.rst
- python/marvin/utils/dap/bpt.py
- setup.cfg
This PR fixes a bug in the `get_bpt` method for `matplotlib>3.5`, where the `add_all` kwarg was removed from `ImageGrid` class.
> Fixes bug in bpt method

- CHANGELOG.rst
- docs/sphinx/whats-new.rst
- python/marvin/utils/datamodel/query/MPL.py
- python/marvin/utils/datamodel/query/__init__.py
- python/marvin/utils/datamodel/query/base.py
This removes MPLs 4-6, and 8-10 from the Query datamodel, and fixes the "allowed releases" the Query tool can see, to prevent the following error. 
```
[WARNING]: Could not remotely retrieve full set of parameters. Requests Http Status Error: 409 Client Error: CONFLICT for url: https://sas.sdss.org/marvin/api/query/getparamslist/ (MarvinUserWarning)
```
This warning occurs when marvin makes a request from the server for the allowed query parameters for a release that no longer exists in the database.
> Removes old MPLs from the Query datamodel

- CHANGELOG.rst
- setup.cfg
This PR pins `marvin_brain` and `marvin_wtforms_alchemy` for last release to support python versions >2.7, <3.7.
> Pinning some deps for

- .github/workflows/build.yml
- CHANGELOG.rst
- setup.cfg
This PR bumps the minimum python requirement to python 3.8 and relaxes the upper limit on most package dependencies.
> Relax deps and bump min python to >3.8

- CHANGELOG.rst
- python/marvin/__init__.py
- python/marvin/tools/maps.py
- python/marvin/tools/mixins/dapall.py
- python/marvin/tools/modelcube.py
- python/marvin/utils/datamodel/query/forms.py
- python/marvin/utils/general/general.py
- python/marvin/web/__init__.py
- python/marvin/web/controllers/galaxy.py
- python/marvin/web/extensions.py
- python/marvin/web/flask_jsglue.py
- python/marvin/web/jinja_filters.py
- setup.cfg
- tests/core/test_config.py
This PR updates the Flask package dependencies to `Flask >2`, `Jinja2 > 3`, `werkzeug > 2.0, < 2.1`.  It removes the pip package `Flask-JSGlue` and replaces it with a manual module of version 0.3.1 with the fixed syntax using the `markupsafe` package.  `Flask-JSGlue` does not appear to be regularly maintained right now.  
It also fixes an issue with `WTForms >3` where a String Field was no longer correctly rendering a url. Wrapping it in `flask.Markup` resolves the issue.   
Pinning numpy to >1.20 and switching use of `np.int` and `np.float` to `int` and `float` to clear deprecation warnings.  Switching use of `distutils` to `packaging.version` to clear deprecation warnings.
> Updating Flask package dependencies

- readthedocs.yml
This PR bumps the readthedocs python build version to 3.9.
> Bump rtd python version

- CHANGELOG.rst
- docs/sphinx/conf.py
- docs/sphinx/index.rst
- docs/sphinx/server_change.rst
- docs/sphinx/tools/aperture.rst
- docs/sphinx/tools/utils/plot-map.rst
- docs/sphinx/tutorials/exercises/marvin_kinematics_solution.ipynb
- docs/sphinx/tutorials/lean-tutorial.rst
- docs/sphinx/tutorials/notebooks/lean-tutorial.ipynb
- docs/sphinx/tutorials/plotting-tutorial.rst
- python/marvin/__init__.py
- python/marvin/tools/mixins/aperture.py
- python/marvin/tools/quantities/spectrum.py
- python/marvin/utils/dap/bpt.py
- python/marvin/utils/datamodel/query/base.py
- python/marvin/utils/plot/map.py
- python/marvin/utils/plot/scatter.py
- tests/core/test_config.py
This PR closes #811 and makes the default API url point to the new JHU server home of ``magrathea.sdss.org``.   This option was already present but now the ``config.sasurl`` is forced to always point there.  
It also changes the ``matplotlib`` plot style from ``seaborn-darkgrid`` to ``seaborn-v0.8-darkgrid``.  See https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#seaborn-styles-renamed. 
It also changes the `photutils` syntax from `photutils.Aperture` to `photutils.aperture.Aperture` to avoid deprecation.
> Switch default api server url to JHU

- .bumpversion.cfg
- .github/workflows/docker.yml
- CHANGELOG.rst
- docker/Dockerfile
- docker/Dockerfile.dev
- docker/README.md
- docker/docker-compose-dev.yml
- docker/gunicorn_config.py
- python/marvin/web/templates/header.html
- python/marvin/web/web_utils.py
- setup.cfg
This PR fixes some issues with the docker image and build.  It removes the user login info from the UI header to fix a bug with a missing parameter that arose after the auth removal.  It also adds the docker build to the Github Action workflow.
> Updates to docker build
